added authorization
ChNikS/ror_project pull request #12
Opened 2016-10-17 18:55 UTC by ChNikS

2016-10-18 11:00 UTC, palkan requested changes
А как же проверки самих действий в контроллере?

2016-10-18 13:54 UTC, ChNikS commented
Имеется в виду в спеках для контроллеров проверить случаи, когда другой пользователь пытается получить доступ к чужим данным?

2016-10-18 13:55 UTC, palkan commented
Не, имеется в виду использовать CanCan в контроллерах для проверок (вместо тех, что мы писали сами).

2016-10-18 14:03 UTC, ChNikS commented
А. Понял. Мой Косяк. Просто переносил с другого компа, поэтому не перенес обновленные контроллеры

2016-10-19 13:50 UTC, ChNikS commented
Владимир, я обновил контроллеры. Вы получили ссылку через teachbase, просто при отправке задания у меня вырубился интернет, поэтому некоторое время не показывалось, что задание на рассмотрении.

2016-10-20 17:18 UTC, merged