Task6
ChNikS/ror_project pull request #6
Opened 2016-09-17 17:13 UTC by ChNikS

2016-09-18 15:05 UTC, palkan commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Что будет, если кликнуть на добавление файла, файл при этом не прикрепить, попробовать сохранить ответ?

2016-09-18 15:05 UTC, palkan commented on app/models/answer.rb
> +  has_many :attachments, as: :attachmentable
`dependent`?

2016-09-18 15:06 UTC, palkan commented on db/migrate/20160912200701_cover_attachmen_to_polymorphic.rb
> +    remove_index :attachments, :question_id
Пункт 2\* http://connect.thinknetica.com/t/topic/1152

2016-09-18 15:07 UTC, palkan commented on public/uploads/tmp/1473590790-17680-0001-5126/a.txt
> +text file for question
Папку `upload` не надо хранить в репозитории

2016-09-18 15:09 UTC, palkan requested changes
1. Нет возможности удалить прикрепленный файл после добавления (сценарий "я передумал, хочу загрузить другой или удалить вообще").
2. Нужны acceptance тесты на прикрепление файлов при редактировании (сейчас только при создании).
3. Нужны тесты на удаление файлов при редактировании (у нас есть ответ с файлами, нажимаем редактировать, удаляем один файл и прикрепляем новый).

2016-09-18 16:08 UTC, ChNikS commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Да. Вроде создается нормально

2016-09-19 19:42 UTC, palkan commented on app/views/questions/edit.html.slim
> +    - @question.attachments.each do |a|
Здесь проблема в том, что  у тебя сначала идет текст для элемента (`p Attachment`), а потом внутри ты пишешь выражение. В итоге Slim воспринимает это все как текст (с интерполяцией, которая приводит к ошибке).

Нужно сделать по типу того, как у тебя в show:

```slim
p Attachments:
p
  ul.attachment
    - @question.attachments.each do |a|
       ....
```

2016-10-03 12:14 UTC, merged